version: "1"

services:
  nexus:
    image: gitlab.ti8m.ch:5043/ti8m-forge-internal/docker-nexus3
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
  
volumes:
  nexus-data: {}
